# QLogger - A tiny Qt logging framework. 
#
# MIT License
# Copyright (c) 2013 sandro fadiga
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software
# and associated documentation files (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge, publish, distribute,
# sublicense, and/or sell copies of the Software, and to permit persons to whom the Software
# is furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all copies
# or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
# AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Example configuration file for QLogger

# line comment 

# first configuration will log to warn level to a file on c:\ with 10Mb of size 

[file]
level=warn
outputType=text

# 100kb file
maxFileSize=100k
path=c:/temp/

# second config will log to console with trace level and customized log text mask 
[cons]
level=trace
outputType=console
logMask=time:%t owner:%o level:%l function:%f line:%n message:%m

# third a xml output 
[xml]
level=trace
outputType=xml
fileName=XML_log_%1_%2_%3.xml
path=c:/temp/
